# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
memory_limit = 128000000
bytecode_hash = "none"
evm_version = "cancun"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.25"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
mainnet = { key = "${API_KEY_ETHERSCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
sepolia = "https://rpc2.sepolia.org"
gnosis = "https://rpc.ankr.com/gnosis"
arbitrum = "https://rpc.ankr.com/arbitrum"
base = "https://rpc.ankr.com/base"
localhost = "http://localhost:8545"
